/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import conexion.ConexionBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JUAN MANUEL
 */
public class concesionario_marca extends javax.swing.JPanel {

    static ResultSet res;
    
    /**
     * Creates new form concesionario_marca
     */
    public concesionario_marca() {
        initComponents();
        cargarunion();
    }

    
    public void cargarunion(){
        DefaultTableModel modelo = (DefaultTableModel)Union_marca.getModel();
        modelo.setRowCount(0);
         ConexionBD cc = new ConexionBD(); //creo clase conxeion base de datos
        Connection cn = cc.getConnection();//creo variable para iniciar la conexion
        PreparedStatement pst = null;  // sirve para hacer los llamados de la base
        String sql ="SELECT * FROM marca,concesionario WHERE marca.Concesionario_idConcecionario = idConcecionario ";
        
        try {
            
         pst=cn.prepareStatement(sql);
          ResultSet rs = pst.executeQuery();
          while(rs.next()){
              Vector v =new Vector();
              v.add(rs.getInt(1));
              v.add(rs.getString(2));
               v.add(rs.getInt(3));
               v.add(rs.getString(4));
               v.add(rs.getString(5));
               modelo.addRow(v);
               Union_marca.setModel(modelo);
              
              
          }
              
             
        
    }catch(SQLException e){
    
}
    }
        
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Union_marca = new javax.swing.JTable();

        Union_marca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Union_marca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Marca", "Marca", "ID Concesionario", "Nombre", "Direccion"
            }
        ));
        jScrollPane2.setViewportView(Union_marca);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Union_marca;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
