/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import conexion.ConexionBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JUAN MANUEL
 */
public class Consulta_Marca_Concesionario extends javax.swing.JPanel {

    /**
     * Creates new form Consulta_Marca_Concesionario
     */
    public Consulta_Marca_Concesionario() {
        initComponents();
        cargarunion();
    }
 public void cargarunion(){
        DefaultTableModel modelo = (DefaultTableModel)union_modelo.getModel();
        modelo.setRowCount(0);
         ConexionBD cc = new ConexionBD(); //creo clase conxeion base de datos
        Connection cn = cc.getConnection();//creo variable para iniciar la conexion
        PreparedStatement pst = null;  // sirve para hacer los llamados de la base
        String sql ="SELECT id_modelo,nombre_modelo,nombre_marca,nombre_concesionario FROM modelo,marca,concesionario WHERE modelo.id_modelo = marca.id_marca && marca.id_concesionario = concesionario.id_concesionario";
        
        try {
            
         pst=cn.prepareStatement(sql);
          ResultSet rs = pst.executeQuery();
          while(rs.next()){
              Vector v =new Vector();
              v.add(rs.getInt(1));
              v.add(rs.getString(2));
               v.add(rs.getString(3));
               v.add(rs.getString(4));
               modelo.addRow(v);
               union_modelo.setModel(modelo);
              
              
          }
              
             
        
    }catch(SQLException e){
    
}
    }
        
    
    
    /*

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        union_modelo = new javax.swing.JTable();

        union_modelo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Modelo", "Marca", "Concesionario"
            }
        ));
        jScrollPane1.setViewportView(union_modelo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable union_modelo;
    // End of variables declaration//GEN-END:variables
}
